export const technologies = [
    { name: "Ionic", logo: "/logos/ionic.svg" },
    { name: "Android Studio", logo: "/logos/android.svg" },
    { name: "React", logo: "/logos/react.svg" },
    { name: "Node.js", logo: "/logos/nodejs.svg" },
    { name: "Typescript", logo: "/logos/typescript.svg" },
    { name: "GPT API", logo: "/logos/gpt.svg" },
    { name: "Prompt engineering", logo: "/logos/prompt.svg" },
    { name: "threeJS", logo: "/logos/threejs.svg" },
    { name: "Capacitor", logo: "/logos/capacitor.svg" },
    { name: "Firestore", logo: "/logos/firestore.png" },
    { name: "Cypress", logo: "/logos/cypress.svg" },
    { name: "Firebase Auth", logo: "/logos/firebase.png" },
    { name: "Ruby on Rails", logo: "/logos/ruby-on-rails.svg" },
    { name: "PostgresQL", logo: "/logos/postgresql.svg" },
    { name: "Styled components", logo: "/logos/styled-components.jpeg" },
    { name: "Render", logo: "/logos/render.svg" },
    { name: "Expo", logo: "/logos/expo.png" },
    { name: "NextJS", logo: "/logos/nextjs.svg" },
    { name: "React Native", logo: "/logos/react.svg" },
    { name: "react-three-fiber", logo: "/logos/threejs.svg" },
    { name: "AWS", logo: "/logos/aws.svg" },
    { name: "EC2", logo: "/logos/ec2.svg" },
    { name: "Material UI", logo: "/logos/material-ui.svg" },
    { name: "Prisma", logo: "/logos/prisma.svg" },
    { name: "GraphQL", logo: "/logos/graphql.png" },
    { name: "Apollo", logo: "/logos/apollo.svg" },
    { name: "RDS", logo: "/logos/rds.svg" },
    { name: "redux", logo: "/logos/redux.svg" },
    { name: "Tailwind CSS", logo: "/logos/tailwind-css.svg" },
    { name: "SASS", logo: "/logos/sass.svg" },
    { name: "Jest", logo: "/logos/jest.svg" },
    { name: "Supabase", logo: "/logos/supabase.svg" },
    { name: "Storybook", logo: "/logos/storybook.svg" },
];
